AlternateScreen=true
MpvArgs=[]
StoragePath=$HOME/.local/share/curd
MyAnimeListClientSecret=
MyAnimeListImportDismissed=false
AnimeNameLanguage=english
SkipRecap=false
SkipOp=false
VimKeys=false
MenuOrder=CONTINUE_LAST,CURRENT,ALL,UNTRACKED
TrackingConfigured=true
TrackingLocal=true
AddMissingOptions=true
ManualProviderSearch=false
SubsLanguage=english
DisabledProviders=[]
SubOrDub=sub
PercentageToMarkComplete=85
SkipEd=false
MpvEpisodePlaylist=true
RofiSelection=false
ScoreOnCompletion=false
ImagePreview=false
DiscordPresence=false
MyAnimeListImported=false
CheckUpdates=false
NextEpisodePrompt=true
MpvPlaybackStartTimeout=20
TrackingRemote=none
Provider=stacked
Player=mpv
SaveMpvSpeed=false
MyAnimeListClientID=disabled_mal_not_used
SubStyle=soft
SkipFiller=false
