AddMissingOptions=true
AlternateScreen=true
AnimeNameLanguage=english
CheckUpdates=false
DisabledProviders=[]
DiscordPresence=false
ImagePreview=false
ManualProviderSearch=false
MenuOrder=CONTINUE_LAST,CURRENT,ALL,UNTRACKED
MpvArgs=[]
MpvEpisodePlaylist=true
MpvPlaybackStartTimeout=20
MyAnimeListClientID=disabled_mal_not_used
MyAnimeListClientSecret=
MyAnimeListImportDismissed=false
MyAnimeListImported=false
NextEpisodePrompt=true
PercentageToMarkComplete=85
Player=mpv
Provider=stacked
RofiSelection=false
SaveMpvSpeed=false
ScoreOnCompletion=false
SkipEd=false
SkipFiller=false
SkipOp=false
SkipRecap=false
StoragePath=$HOME/.local/share/curd
SubOrDub=sub
SubStyle=soft
SubsLanguage=english
TrackingConfigured=true
TrackingLocal=true
TrackingRemote=none
VimKeys=false
