# General
CheckUpdates=false
AddMissingOptions=false
StoragePath=$HOME/.local/share/curd

# Selection & UI
AnimeNameLanguage=english
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,REMAP_PROVIDER,CONTINUE_LAST,TRACKER,PROVIDER
AlternateScreen=true
VimKeys=false
RofiSelection=true
ImagePreview=true
NextEpisodePrompt=true

# Provider
Provider=stacked
DisabledProviders=[]
ManualProviderSearch=false

# Player (mpv)
Player=mpv
MpvArgs=[]
MpvEpisodePlaylist=true
MpvPlaybackStartTimeout=20
SaveMpvSpeed=false

# Audio & Subtitles
SubOrDub=sub
SubStyle=soft
SubsLanguage=english

# Skip Behavior
SkipRecap=false
SkipOp=false
SkipEd=false
SkipFiller=false

# Tracking & Social
DiscordPresence=false
TrackingRemote=none
TrackingLocal=true
TrackingConfigured=true
MyAnimeListImported=false
MyAnimeListImportDismissed=false
ScoreOnCompletion=false
PercentageToMarkComplete=85
