[tools]
babashka = "latest"
bat = "latest"
bottom = "latest"
chezmoi = "latest"
clojure = "latest"
delta = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
gocryptfs = "latest"
helix = "latest"
hledger = "latest"
jaq = "latest"
java = "latest"
jj = "latest"
jq = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
starship = "latest"
typst = "latest"
watchexec = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
