[tools]
carapace = "latest"
"cargo:bacon" = "latest"
"cargo:feedr" = "latest"
"cargo:loco" = "latest"
"cargo:sea-orm-cli" = "latest"
fastfetch = "latest"
rust = "latest"
starship = "latest"
zoxide = "latest"
