[tools]

# RUST
rust = "latest"
"cargo:bacon" = "latest"
"cargo:loco" = "latest"
"cargo:sea-orm-cli" = "latest"

# JVM
java = "latest"
babashka = { version = "latest", exe = "bb" }
clojure = "latest"

# PYTHON
python = "latest"
uv = "latest"

# RUBY
ruby = "latest"

# GO
go = "latest"

# CLI TOOLS
carapace = "latest"
fastfetch = "latest"
starship = "latest"
usql = "latest"
zoxide = "latest"
"cargo:weathr" = "latest"

# RANDOM DEPENDECIES (MOSTLY FOR DOOM DOCTOR)
"cargo:emacs-lsp-booster" = "latest"
"cargo:justinbarclay/parinfer-rust-emacs" = { version = "latest", locked = false }
"go:github.com/jessfraz/dockfmt" = "latest"
"go:github.com/chrishrb/go-grip" = "latest"
"pipx:pyflakes" = "latest"
black = "latest"
# SORT ME
