# theme = "catppuccin_latte"       # light
theme = "catppuccin_macchiato" # dark

[editor]
color-modes = true
cursorline = true
popup-border = "all"
insert-final-newline = true
trim-final-newlines = true
trim-trailing-whitespace = true
rainbow-brackets = true
cursor-shape.insert = "bar"
whitespace.render.tab = "all"
buffer-picker.start-position = "previous"

[keys.normal]
"A-x" = "command_palette"
[keys.insert]
"A-x" = "command_palette"
[keys.select]
"A-x" = "command_palette"
