#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "doctorkotik187"
email = "217476020+doctorkotik187@users.noreply.github.com"

[signing]
backend = "ssh"
key = "~/.ssh/dk-sign.pub"
behavior = "own"

[lazyjj]
layout-percent = 25
