onboarding = false

[terminal]
default_shell = "nu"

[ui]
mouse_capture = false

[theme]
# name = "catppuccin-latte"
name = "catppuccin"

[keys]
focus_pane_up     = "alt+up"
focus_pane_down   = "alt+down"
focus_pane_left   = "alt+left"
focus_pane_right  = "alt+right"
previous_tab      = "alt+shift+left"
next_tab          = "alt+shift+right"
switch_tab        = "alt+1..9"
move_tab_previous = "alt+i"
move_tab_next     = "alt+o"

[[keys.command]]
key     = "prefix+y"
type    = "shell"
command = "herdr pane read $HERDR_ACTIVE_PANE_ID --source recent-unwrapped --lines 2000 | wl-copy"
description = "yank pane contents to clipboard"
